name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  gap: ^3.0.1
  email_validator: ^2.1.17
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    # - assets/images/rectangle_1093.png
    # - assets/images/ellipse_308.png
    # - assets/images/ellipse_3871.jpeg
    # - assets/images/rectangle_1092.png
    # - assets/images/ellipse_304.png
    # - assets/images/rectangle_1151.png
    # - assets/images/rectangle_1161.png
    # - assets/images/ellipse_386.jpeg
    # - assets/vectors/user.svg
    # - assets/vectors/videoicon.svg
    # - assets/vectors/settings.svg
    # - assets/vectors/path_5_x2.svg
    # - assets/vectors/path_20_x2.svg
    # - assets/vectors/vector_18_x2.svg
    # - assets/vectors/path_10_x2.svg
    # - assets/vectors/vector_37_x2.svg
    # - assets/vectors/vector_x2.svg
    # - assets/vectors/vector_12_x2.svg
    # - assets/vectors/exclude_36_x2.svg
    # - assets/vectors/vector_19_x2.svg
    # - assets/vectors/vector_36_x2.svg
    # - assets/vectors/path_11_x2.svg
    # - assets/vectors/container_16_x2.svg
    # - assets/vectors/vector_53_x2.svg
    # - assets/vectors/path_6_x2.svg
    # - assets/vectors/vector_26_x2.svg
    # - assets/vectors/vector_43_x2.svg
    # - assets/vectors/container_2_x2.svg
    # - assets/vectors/container_8_x2.svg
    # - assets/vectors/path_12_x2.svg
    # - assets/vectors/vector_15_x2.svg
    # - assets/vectors/vector_17_x2.svg
    # - assets/vectors/vector_33_x2.svg
    # - assets/vectors/vector_21_x2.svg
    # - assets/vectors/vector_30_x2.svg
    # - assets/vectors/path_25_x2.svg
    # - assets/vectors/path_26_x2.svg
    # - assets/vectors/path_22_x2.svg
    # - assets/vectors/path_19_x2.svg
    # - assets/vectors/vector_5_x2.svg
    # - assets/vectors/vector_14_x2.svg
    # - assets/vectors/vector_10_x2.svg
    # - assets/vectors/path_4_x2.svg
    # - assets/vectors/exclude_20_x2.svg
    # - assets/vectors/path_32_x2.svg
    # - assets/images/ellipse_318.jpeg
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/rectangle_1161.png
    # - assets/images/rectangle_1150.jpeg
    # - assets/images/rectangle_1093.png
    # - assets/images/rectangle_1151.png
    # - assets/images/ellipse_308.png
    # - assets/vectors/exclude_12_x2.svg
    # - assets/vectors/ellipse_306_x2.svg
    # - assets/vectors/exclude_6_x2.svg
    # - assets/vectors/vector_31_x2.svg
    # - assets/vectors/container_9_x2.svg
    # - assets/vectors/vector_45_x2.svg
    # - assets/vectors/vector_6_x2.svg
    # - assets/vectors/vector_1_x2.svg
    # - assets/vectors/vector_13_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/images/rectangle_1156.jpeg
    # - assets/images/rectangle_1154.jpeg
    # - assets/images/rectangle_1151.png
    # - assets/images/rectangle_1155.jpeg
    # - assets/vectors/path_21_x2.svg
    # - assets/vectors/vector_34_x2.svg
    # - assets/vectors/exclude_x2.svg
    # - assets/vectors/rectangle_772_x2.svg
    # - assets/vectors/path_27_x2.svg
    # - assets/vectors/exclude_23_x2.svg
    # - assets/vectors/vector_51_x2.svg
    # - assets/vectors/vector_1906_x2.svg
    # - assets/vectors/container_13_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/vectors/group_11_x2.svg
    # - assets/vectors/exclude_10_x2.svg
    # - assets/vectors/vector_1907_x2.svg
    # - assets/vectors/exclude_37_x2.svg
    # - assets/images/ellipse_3071.png
    # - assets/images/rectangle_1093.png
    # - assets/images/rectangle_1151.png
    # - assets/images/ellipse_304.png
    # - assets/images/ellipse_302.jpeg
    # - assets/images/ellipse_300.jpeg
    # - assets/images/splash.png
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/ellipse_386.jpeg
    # - assets/images/rectangle_1150.jpeg
    # - assets/images/ellipse_3871.jpeg
    # - assets/images/ellipse_308.png
    # - assets/images/rectangle_1092.png
    # - assets/vectors/vector_9_x2.svg
    # - assets/vectors/vector_2_x2.svg
    # - assets/vectors/vector_49_x2.svg
    # - assets/vectors/vector_4_x2.svg
    # - assets/vectors/container_6_x2.svg
    # - assets/vectors/exclude_13_x2.svg
    # - assets/vectors/container_18_x2.svg
    # - assets/vectors/container_4_x2.svg
    # - assets/vectors/exclude_17_x2.svg
    # - assets/vectors/vector_7_x2.svg
    # - assets/images/rectangle_1151.png
    # - assets/vectors/rectangle_1052_x2.svg
    # - assets/vectors/rectangle_10551_x2.svg
    # - assets/vectors/rectangle_1062_x2.svg
    # - assets/vectors/rectangle_10612_x2.svg
    # - assets/vectors/path_x2.svg
    # - assets/vectors/rectangle_11317_x2.svg
    # - assets/vectors/rectangle_10451_x2.svg
    # - assets/vectors/vector_1905_x2.svg
    # - assets/vectors/rectangle_1051_x2.svg
    # - assets/vectors/rectangle_10491_x2.svg
    # - assets/vectors/rectangle_1060_x2.svg
    # - assets/vectors/rectangle_10541_x2.svg
    # - assets/vectors/rectangle_10571_x2.svg
    # - assets/vectors/rectangle_10431_x2.svg
    # - assets/vectors/rectangle_113113_x2.svg
    # - assets/vectors/rectangle_10592_x2.svg
    # - assets/vectors/rectangle_10442_x2.svg
    # - assets/vectors/rectangle_1063_x2.svg
    # - assets/vectors/vector_8963_x2.svg
    # - assets/vectors/vector_44_x2.svg
    # - assets/vectors/rectangle_10471_x2.svg
    # - assets/vectors/exclude_33_x2.svg
    # - assets/vectors/path_29_x2.svg
    # - assets/vectors/rectangle_10581_x2.svg
    # - assets/vectors/camera_012_x2.svg
    # - assets/vectors/rectangle_10561_x2.svg
    # - assets/vectors/rectangle_1132_x2.svg
    # - assets/vectors/rectangle_774_x2.svg
    # - assets/vectors/rectangle_10501_x2.svg
    # - assets/vectors/path_17_x2.svg
    # - assets/vectors/vector_32_x2.svg
    # - assets/vectors/exclude_35_x2.svg
    # - assets/vectors/rectangle_10461_x2.svg
    # - assets/vectors/rectangle_11315_x2.svg
    # - assets/vectors/rectangle_1053_x2.svg
    # - assets/vectors/rectangle_10481_x2.svg
    # - assets/vectors/rectangle_11313_x2.svg
    # - assets/vectors/group_8_x2.svg
    # - assets/vectors/rectangle_11314_x2.svg
    # - assets/images/ellipse_318.jpeg
    # - assets/images/ellipse_3041.jpeg
    # - assets/vectors/group_13_x2.svg
    # - assets/vectors/combo_shape_x2.svg
    # - assets/vectors/exclude_7_x2.svg
    # - assets/vectors/rectangle_771_x2.svg
    # - assets/vectors/group_7_x2.svg
    # - assets/vectors/exclude_29_x2.svg
    # - assets/images/ellipse_386.jpeg
    # - assets/images/rectangle_1151.png
    # - assets/images/ellipse_308.png
    # - assets/images/ellipse_3041.jpeg
    # - assets/images/ellipse_387.jpeg
    # - assets/images/ellipse_304.png
    # - assets/images/ellipse_3871.jpeg
    # - assets/images/rectangle_1150.jpeg
    # - assets/images/ellipse_3861.jpeg
    # - assets/vectors/union_3_x2.svg
    # - assets/vectors/exclude_5_x2.svg
    # - assets/vectors/group_394_x2.svg
    # - assets/vectors/vector_54_x2.svg
    # - assets/vectors/off_1_x2.svg
    # - assets/vectors/group_5_x2.svg
    # - assets/vectors/group_393_x2.svg
    # - assets/vectors/exclude_15_x2.svg
    # - assets/vectors/vector_52_x2.svg
    # - assets/vectors/union_2_x2.svg
    # - assets/vectors/icon_1_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/vectors/vector_1902_x2.svg
    # - assets/vectors/group_10_x2.svg
    # - assets/vectors/exclude_24_x2.svg
    # - assets/vectors/exclude_30_x2.svg
    # - assets/images/ellipse_3871.jpeg
    # - assets/images/splash.png
    # - assets/images/rectangle_1150.jpeg
    # - assets/images/rectangle_1151.png
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/ellipse_304.png
    # - assets/images/rectangle_1093.png
    # - assets/images/rectangle_1092.png
    # - assets/images/ellipse_300.jpeg
    # - assets/images/ellipse_302.jpeg
    # - assets/images/ellipse_386.jpeg
    # - assets/images/ellipse_3071.png
    # - assets/images/ellipse_308.png
    # - assets/vectors/vector_25_x2.svg
    # - assets/vectors/container_11_x2.svg
    # - assets/vectors/vector_42_x2.svg
    # - assets/vectors/exclude_22_x2.svg
    # - assets/vectors/vector_27_x2.svg
    # - assets/vectors/container_15_x2.svg
    # - assets/vectors/exclude_9_x2.svg
    # - assets/vectors/container_12_x2.svg
    # - assets/vectors/vector_38_x2.svg
    # - assets/vectors/vector_47_x2.svg
    # - assets/vectors/vector_3_x2.svg
    # - assets/vectors/vector_8_x2.svg
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/rectangle_1131.jpeg
    # - assets/images/ellipse_307.png
    # - assets/images/ellipse_319.jpeg
    # - assets/images/rectangle_1093.png
    # - assets/images/rectangle_1151.png
    # - assets/vectors/rectangle_1059_x2.svg
    # - assets/vectors/rectangle_1043_x2.svg
    # - assets/vectors/rectangle_10621_x2.svg
    # - assets/vectors/rectangle_10441_x2.svg
    # - assets/vectors/rectangle_1046_x2.svg
    # - assets/vectors/path_14_x2.svg
    # - assets/vectors/rectangle_1054_x2.svg
    # - assets/vectors/rectangle_1050_x2.svg
    # - assets/vectors/rectangle_10602_x2.svg
    # - assets/vectors/rectangle_1055_x2.svg
    # - assets/vectors/rectangle_10452_x2.svg
    # - assets/vectors/rectangle_10572_x2.svg
    # - assets/vectors/vector_190_x2.svg
    # - assets/vectors/rectangle_10521_x2.svg
    # - assets/vectors/vector_8961_x2.svg
    # - assets/vectors/rectangle_10562_x2.svg
    # - assets/vectors/rectangle_10492_x2.svg
    # - assets/vectors/rectangle_10632_x2.svg
    # - assets/vectors/path_2_x2.svg
    # - assets/vectors/rectangle_10582_x2.svg
    # - assets/vectors/rectangle_10611_x2.svg
    # - assets/vectors/rectangle_11318_x2.svg
    # - assets/vectors/exclude_26_x2.svg
    # - assets/vectors/path_16_x2.svg
    # - assets/vectors/rectangle_1048_x2.svg
    # - assets/vectors/exclude_8_x2.svg
    # - assets/vectors/rectangle_10531_x2.svg
    # - assets/vectors/camera_011_x2.svg
    # - assets/vectors/rectangle_113112_x2.svg
    # - assets/vectors/rectangle_11312_x2.svg
    # - assets/vectors/rectangle_10512_x2.svg
    # - assets/vectors/vector_39_x2.svg
    # - assets/vectors/vector_48_x2.svg
    # - assets/vectors/rectangle_113110_x2.svg
    # - assets/vectors/rectangle_775_x2.svg
    # - assets/vectors/rectangle_11316_x2.svg
    # - assets/vectors/group_9_x2.svg
    # - assets/vectors/rectangle_10472_x2.svg
    # - assets/images/rectangle_1151.png
    # - assets/images/ellipse_319.jpeg
    # - assets/images/rectangle_1131.jpeg
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/ellipse_307.png
    # - assets/images/rectangle_1093.png
    # - assets/vectors/exclude_3_x2.svg
    # - assets/vectors/path_31_x2.svg
    # - assets/vectors/rectangle_1049_x2.svg
    # - assets/vectors/rectangle_10432_x2.svg
    # - assets/vectors/vector_1903_x2.svg
    # - assets/vectors/exclude_19_x2.svg
    # - assets/vectors/rectangle_1045_x2.svg
    # - assets/vectors/vector_23_x2.svg
    # - assets/vectors/rectangle_113115_x2.svg
    # - assets/vectors/rectangle_10482_x2.svg
    # - assets/vectors/rectangle_1058_x2.svg
    # - assets/vectors/rectangle_10532_x2.svg
    # - assets/vectors/rectangle_10591_x2.svg
    # - assets/vectors/rectangle_1057_x2.svg
    # - assets/vectors/path_7_x2.svg
    # - assets/vectors/path_28_x2.svg
    # - assets/vectors/rectangle_10601_x2.svg
    # - assets/vectors/rectangle_10552_x2.svg
    # - assets/vectors/rectangle_10511_x2.svg
    # - assets/vectors/rectangle_1047_x2.svg
    # - assets/vectors/group_14_x2.svg
    # - assets/vectors/rectangle_1044_x2.svg
    # - assets/vectors/rectangle_10631_x2.svg
    # - assets/vectors/vector_16_x2.svg
    # - assets/vectors/rectangle_113111_x2.svg
    # - assets/vectors/rectangle_11311_x2.svg
    # - assets/vectors/rectangle_113114_x2.svg
    # - assets/vectors/rectangle_1056_x2.svg
    # - assets/vectors/rectangle_10622_x2.svg
    # - assets/vectors/rectangle_10522_x2.svg
    # - assets/vectors/camera_01_x2.svg
    # - assets/vectors/camera_x2.svg
    # - assets/vectors/user_x2.svg
    # - assets/vectors/doc_x2.svg
    # - assets/vectors/rectangle_773_x2.svg
    # - assets/vectors/vector_41_x2.svg
    # - assets/vectors/rectangle_10502_x2.svg
    # - assets/vectors/group_6_x2.svg
    # - assets/vectors/rectangle_10542_x2.svg
    # - assets/vectors/rectangle_10462_x2.svg
    # - assets/vectors/vector_8962_x2.svg
    # - assets/vectors/rectangle_1061_x2.svg
    # - assets/vectors/rectangle_11319_x2.svg
    # - assets/images/ellipse_3071.png
    # - assets/images/rectangle_1161.png
    # - assets/vectors/vector_35_x2.svg
    # - assets/vectors/path_24_x2.svg
    # - assets/vectors/path_23_x2.svg
    # - assets/vectors/vector_19010_x2.svg
    # - assets/vectors/vector_20_x2.svg
    # - assets/vectors/container_17_x2.svg
    # - assets/vectors/vector_24_x2.svg
    # - assets/vectors/container_7_x2.svg
    # - assets/vectors/container_x2.svg
    # - assets/vectors/container_3_x2.svg
    # - assets/vectors/container_5_x2.svg
    # - assets/vectors/container_14_x2.svg
    # - assets/vectors/exclude_28_x2.svg
    # - assets/vectors/container_1_x2.svg
    # - assets/vectors/container_10_x2.svg
    # - assets/vectors/subtract_x2.svg
    # - assets/vectors/exclude_18_x2.svg
    # - assets/vectors/path_9_x2.svg
    # - assets/vectors/path_30_x2.svg
    # - assets/vectors/vector_50_x2.svg
    # - assets/vectors/vector_28_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/vectors/exclude_4_x2.svg
    # - assets/vectors/group_1_x2.svg
    # - assets/vectors/vector_1909_x2.svg
    # - assets/vectors/exclude_21_x2.svg
    # - assets/images/ellipse_318.jpeg
    # - assets/images/image_4011.jpeg
    # - assets/vectors/exclude_11_x2.svg
    # - assets/vectors/group_12_x2.svg
    # - assets/vectors/path_8_x2.svg
    # - assets/vectors/group_4_x2.svg
    # - assets/vectors/path_13_x2.svg
    # - assets/vectors/vector_11_x2.svg
    # - assets/vectors/exclude_25_x2.svg
    # - assets/vectors/group_2_x2.svg
    # - assets/vectors/path_18_x2.svg
    # - assets/vectors/volume_uihut_x2.svg
    # - assets/vectors/vector_1901_x2.svg
    # - assets/images/ellipse_307.png
    # - assets/images/ellipse_3871.jpeg
    # - assets/images/ellipse_427.jpeg
    # - assets/images/rectangle_1093.png
    # - assets/images/ellipse_3071.png
    # - assets/images/ellipse_3042.jpeg
    # - assets/images/rectangle_1151.png
    # - assets/vectors/plus_x2.svg
    # - assets/vectors/plus_2_x2.svg
    # - assets/vectors/plus_4_x2.svg
    # - assets/vectors/group_3_x2.svg
    # - assets/vectors/exclude_31_x2.svg
    # - assets/vectors/exclude_32_x2.svg
    # - assets/vectors/plus_5_x2.svg
    # - assets/vectors/vector_1908_x2.svg
    # - assets/vectors/plus_3_x2.svg
    # - assets/vectors/plus_1_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/vectors/exclude_34_x2.svg
    # - assets/vectors/vector_46_x2.svg
    # - assets/vectors/ellipse_1226_x2.svg
    # - assets/vectors/vector_22_x2.svg
    # - assets/vectors/exclude_14_x2.svg
    # - assets/images/splash.png
    # - assets/vectors/exclude_2_x2.svg
    # - assets/vectors/ellipse_1227_x2.svg
    # - assets/vectors/vector_40_x2.svg
    # - assets/vectors/exclude_27_x2.svg
    # - assets/images/rectangle_1161.png
    # - assets/vectors/exclude_1_x2.svg
    # - assets/vectors/group_x2.svg
    # - assets/vectors/exclude_16_x2.svg
    # - assets/vectors/vector_1904_x2.svg
